name: IBM Cloud Auto Restart base3-5

on:
   push:
    branches: [ master ]
   pull_request:
    branches: [ master ]
   schedule:
    - cron: '0 4 * * FRI'

jobs:
  ibm-cloud-restart:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Init
      run: |
        chmod -R 755 ./IBM_Cloud_CLI/
        ./IBM_Cloud_CLI/ibmcloud config --check-version=false
    - name: Login IBM Cloud
      env:
        IBM_ACCOUNT: ${{ secrets.IBM_ACCOUNT_BASE004 }}
        REGION_NUM: ${{ secrets.REGION_NUM_BASE004 }}
      run: |
        ./IBM_Cloud_CLI/ibmcloud login <<EOF
        $IBM_ACCOUNT
        $REGION_NUM
        no
        EOF
    - name: Target IBM Cloud
      env:
        RESOURSE_ID: ${{ secrets.RESOURSE_ID_BASE004 }}
      run: |
        ./IBM_Cloud_CLI/ibmcloud target -g "$RESOURSE_ID"
        ./IBM_Cloud_CLI/ibmcloud target --cf
        ./IBM_Cloud_CLI/ibmcloud cf install -f -v 6.15.0
    - name: Restart IBM Cloud
      env:
        IBM_APP_NAME: ${{ secrets.IBM_APP_NAME_BASE004 }}
      run: |
        ./IBM_Cloud_CLI/ibmcloud cf restart "$IBM_APP_NAME"
    - name: Logout IBM Cloud
      run: |
        ./IBM_Cloud_CLI/ibmcloud logout


